app.title=User Feedback(local)
 
spring.cloud.azure.active-directory.enabled=true
 
spring.cloud.azure.active-directory.profile.tenant-id=6fe7e4ab-29ef-42c6-953b-0f8aaa49db29
 
spring.cloud.azure.active-directory.credential.client-id=727fa184-f3b1-4e4b-b5dc-b4473ec13b4f
 
spring.cloud.azure.active-directory.credential.client-secret=wig8Q~mlcR8ZqgTY4gz53cdz3_MvDoz1nhBCcbr4